version: '3'

services:
    mysql:
      image: kj2149/clase-docker_t_t:v1_mysql-8.3.0
      container_name: mysql_container_2
      environment:
        MYSQL_ROOT_PASSWORD: asd123
        MYSQL_DATABASE: wordpress_db
        MYSQL_USER: wordpress_user
        MYSQL_PASSWORD: asdf1234
      volumes:
        - mysql_data:/var/lib/mysql


    wordpress: 
        image: kj2149/clase-docker_t_t:v1_wordpress-6.5.2-apache
        container_name: wordpress_container_2
        ports:
          - "8080:80"
        environment:
          WORDPRESS_DB_HOST: mysql_container_2
          WORDPRESS_DB_USER: wordpress_user
          WORDPRESS_DB_PASSWORD: asdf1234
          WORDPRESS_DB_NAME: wordpress_db
        depends_on:
          - mysql
        volumes:
          - wordpress_data:/var/www/html

volumes:
  mysql_data:
  wordpress_data: